### ISSUE TITLE
List a space

### ISSUE THREAD

**Issue by gabrielabud** [cazwazacz/MakersBnB#2]
As a host
So I can make money from my spare room
I want to be able to list a space

**Comment by antoniobelmar** [comment]
1 - Add database cleaner
2 - Set up datamapper config file
3 - Rakefile to clean database tasks
4 - Create development db
5 - Test and development dbs
6 - Deploy to Heroku

**Comment by noitscassie** [comment]
Added database_cleaner :smile_cat:

**Comment by noitscassie** [comment]
Completed task 2 :shipit:

**Comment by noitscassie** [comment]
Completed task 4 & 5 :shipit: (we put the tasks in the wrong order initially)

**Comment by noitscassie** [comment]
Completed task 3 :shipit:
